[project]
name = "uta-gestion-ops"
version = "0.1.0"
description = "An application to manage payment orders for UTA"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "nicegui>=3.0.4",
    "pywebview>=6.0",
    "sqlalchemy>=2.0.44",
    "weasyprint>=66.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]

packaging = ["pyinstaller>=6.16.0"]

[tool.uv]
default-groups = "all"

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
]

[tool.ruff.lint.isort]
known-first-party = ["src"]
lines-after-imports = 2