[project]
name = "uta-gestion-ops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "nicegui>=3.0.4",
    "pywebview>=6.0",
    "sqlalchemy>=2.0.44",
    "weasyprint>=66.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "selenium>=4.37.0",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
main_file = "main.py"
addopts = "-p nicegui.testing.plugin"
